### ISSUE TITLE
Interactivity stops working after dragging

### ISSUE THREAD

**Issue by MateoV** [cutting-room-floor/easey-DEAD#12]
Load the page, interactivity working. Zoom in/out, still works. Drag the map, it stops working and mouse pointer is stuck on "grab" icon. Using Wax 4.1.8 and Modest Maps 0.20.0.

Implementation consists of these and nothing else:
new easey.DragHandler(),
new easey.TouchHandler(),
new easey.DoubleClickHandler(),
new easey.MouseWheelHandler()

**Comment by leplatrem** [comment]
I reproduce this also, only with dragging like @MateoV said.

With Wax 4.1.5, and latest Easey, using the following piece of code : 

```
    var mm = com.modestmaps;
    var url = '/mymap.jsonp';

    wax.tilejson(url, function(tilejson) {
      var m = new mm.Map('mymap',
        new wax.mm.connector(tilejson),
        null, [
            new easey.DragHandler(),
            new easey.TouchHandler(),
            new easey.DoubleClickHandler(),
            new easey.MouseWheelHandler()
        ]);

      m.setCenterZoom(new mm.Location(tilejson.center[1],
                                      tilejson.center[0]),
                                      tilejson.center[2]);
      wax.mm.zoomer(m).appendTo(m.parent);
      wax.mm.legend(m, tilejson).appendTo(m.parent);
      wax.mm.attribution(m, tilejson).appendTo(m.parent);
      wax.mm.interaction(m, tilejson);
    });
```

**Comment by MateoV** [comment]
Just to update, this is still an issue with latest Wax (6.0.0 beta2) and ModestMaps (1.1.0 alpha) releases. Means we can't use it in any of our projects.

**Comment by ansis** [comment]
I believe this pull request should fix the problem. Does it work you?
https://github.com/mapbox/easey/pull/15

**Comment by MateoV** [comment]
Yes, that did the trick. Merged. Thanks!
