### ISSUE TITLE
.optimal() does not handle the no-panning case correctly

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/easey-DEAD#22]
the code seems to zoom instantly into a random area of the world; it probably needs a double-tap to work correctly here.

**Comment by ansis** [comment]
Can you reproduce it?

It should be handled by https://github.com/mapbox/easey/blob/gh-pages/src/easey.js#L228

**Comment by ansis** [comment]
It was a weird case that only happens when the x and y coordinates are the same.
Fixed in 9789608c8f067053eed62b44843b84384169450c
