### ISSUE TITLE
touchHandler and android

### ISSUE THREAD

**Issue by ansis** [cutting-room-floor/easey-DEAD#29]
It seems the touchHandler isn't working with android.

Support tickets:
http://support.mapbox.com/discussions/general-questions/3300-mapboxjs-support-for-touch-screen-devices
http://support.mapbox.com/discussions/mapbox-tiles/397-no-panning-on-android-with-mapboxjs-api

**Comment by ansis** [comment]
It looks like its a problem with [`isTouchable`](https://github.com/mapbox/easey/blob/b91fd24c0785bd36feb0b9eb61d2cb067aabca07/src/easey.handlers.js#L104) returning a false negative. I think the best course of action may be to not even try to detect whether a browser is touchable. Take a look at the `remove-istouchable` branch. f73bea3eb3dca482cab636a976edc1edc2409f33

I don't really have the ability to test multitouch android, but it seems to make panning work.

thoughts @tmcw?

**Comment by tmcw** [comment]
Memory might not be perfect, but isTouchable came about because of IE issues with removing handlers for events that don't exist. Removing isTouchable might be doable if we make sure that that isn't problematic, or can do something silly like a try/catch.

**Comment by ansis** [comment]
f73bea3eb3dca482cab636a976edc1edc2409f33 should be fine then, since it will only try removing the handler if a touchstart event has been received (no problems with adding nonexistent handlers, right?). Try/catch would work too

**Comment by willwhite** [comment]
Assigned to [Tender discussion #3300](http://support.mapbox.com/discussions/general-questions/3300-mapboxjs-support-for-touch-screen-devices).

**Comment by willwhite** [comment]
Assigned to [Tender discussion #397](http://support.mapbox.com/discussions/mapbox-tiles/397-no-panning-on-android-with-mapboxjs-api).

**Comment by ansis** [comment]
Fixed and tested in f73bea3eb3dca482cab636a976edc1edc2409f33
