### ISSUE TITLE
Precise is broken on mouseWheelHandler

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/easey-DEAD#31]
See [this example](http://bl.ocks.org/3900729). The code that did correct handling of `.precise()` has been lost at some point.

**Comment by ansis** [comment]
Looks like this broke in 1638fbb802553105559a1732e00c25e323c00f8a
Whats the correct behaviour for precise? zooming with a smaller step? 
https://github.com/mapbox/easey/compare/precise
